### ISSUE TITLE
Installation Dependencies for npm

### ISSUE THREAD

**Issue by natestutte** [ngregrichardson/clone-bot#2]
Setting up and running the bot with a fresh installation of npm and yarn, I needed to install dependencies that weren't listed in the instructions (eg. dotenv, discord.js, cron). It would be good to have these dependencies noted in the README or a part of the installation (unless I'm missing the instructions somewhere).

**Comment by ngregrichardson** [comment]
You can just run `yarn install` to install all require dependencies https://classic.yarnpkg.com/en/docs/installing-dependencies/#toc-installing-dependencies

**Comment by natestutte** [comment]
> 
> 
> You can just run `yarn install` to install all require dependencies https://classic.yarnpkg.com/en/docs/installing-dependencies/#toc-installing-dependencies

I'm still having issues even after using yarn install within the cloned repository

![image](https://user-images.githubusercontent.com/37859882/129408629-3f1982d2-c449-412f-8b2f-072059326ee2.png)

I'm not sure if I'm doing this wrong, can you let me know?

**Comment by ngregrichardson** [comment]
Try deleting the `node_modules` folder and `package-lock.json` and try running `yarn install` again.

**Comment by ngregrichardson** [comment]
If that doesn't work send your node, npm, and yarn versions
